/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ashary
 */
public final class Barang extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public void emptyFields() {
        this.NamaBarang.setText("");
        this.KodeBarang.setText("");
        this.Satuan.setText("");
        this.Jumlah.setText("");
    }

    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        
        Koneksi DB = new Koneksi();
        this.con = DB.getCon();
        this.stat = DB.getStat();
        
        showDataToTable();
    }
    
    public void showDataToTable() {
        try {
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("Kode");
            tb.addColumn("Nama");
            tb.addColumn("Satuan");
            tb.addColumn("Jumlah");
            this.TableBarang.setModel(tb);
            this.sql = "SELECT * FROM `barang`";
            this.rs = this.stat.executeQuery(this.sql);
            while (this.rs.next()) {
                tb.addRow(new Object[]{
                    this.rs.getString("Kode_brg"),
                    this.rs.getString("Nama_brg"),
                    this.rs.getString("Satuan"),
                    this.rs.getString("Jumlah")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(
                Level.SEVERE, 
                "Data tidak dapat ditampilkan. {0}", 
                ex.getMessage());
        }
    }
    
    public void searchData() {
        try {
            this.sql = "SELECT * FROM `barang` WHERE "
                    + "`Kode_brg` LIKE '%" + this.Search.getText() + "%' OR "
                    + "`Nama_brg` LIKE '%" + this.Search.getText() + "%' LIMIT 1";
            this.rs = this.stat.executeQuery(this.sql);
            while (this.rs.next()) {
                this.KodeBarang.setText(rs.getString("Kode_Brg"));
                this.NamaBarang.setText(rs.getString("Nama_Brg"));
                this.Jumlah.setText(rs.getString("Jumlah"));
                this.Satuan.setText(rs.getString("Satuan"));
                
                this.KodeBarang.setEnabled(false);
                this.SimpanBtn.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(
                Level.SEVERE, 
                "Data tidak dapat ditampilkan. {0}", 
                ex.getMessage());
        }
    }
    
    public void saveData() {
        try {
            this.sql = String.format(
                    "INSERT INTO `barang`"
                    + " (`Kode_brg`, `Nama_brg`, `Satuan`, `Jumlah`) "
                    + "VALUES ('%s', '%s', '%s', '%s')",
                this.KodeBarang.getText(),
                this.NamaBarang.getText(),
                this.Satuan.getText(),
                this.Jumlah.getText()
            );
            this.rs = this.stat.executeQuery(this.sql);
            
            this.emptyFields();
            this.showDataToTable();
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(
                Level.SEVERE, 
                "Tidak dapat menyimpan data. {0}", 
                ex.getMessage());
        }
    }
    
    public void updateData() {
        try {
            this.sql = String.format(
                    "UPDATE `barang` SET "
                    + "`Nama_brg` = '%s',"
                    + "`Satuan` = '%s',"
                    + "`Jumlah` = '%s' WHERE `Kode_brg` = '%s'",
                this.NamaBarang.getText(),
                this.Satuan.getText(),
                this.Jumlah.getText(),
                this.KodeBarang.getText()
            );
            this.rs = this.stat.executeQuery(this.sql);
            this.KodeBarang.setEnabled(true);
            this.SimpanBtn.setEnabled(true);
            this.Search.setText("");
            this.emptyFields();
            this.showDataToTable();
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(
                Level.SEVERE, 
                "Tidak dapat menyimpan data. {0}", 
                ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LogoutBtn = new javax.swing.JButton();
        KodeBarangLabel = new javax.swing.JLabel();
        NamaBarangLabel = new javax.swing.JLabel();
        SatuanLabel = new javax.swing.JLabel();
        JumlahLabel = new javax.swing.JLabel();
        KodeBarang = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JTextField();
        Satuan = new javax.swing.JTextField();
        Jumlah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        SimpanBtn = new javax.swing.JButton();
        BatalBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        SearchLabel = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Barang"); // NOI18N

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        KodeBarangLabel.setLabelFor(KodeBarang);
        KodeBarangLabel.setText("Kode Barang");

        NamaBarangLabel.setLabelFor(NamaBarang);
        NamaBarangLabel.setText("Nama Barang");

        SatuanLabel.setLabelFor(Satuan);
        SatuanLabel.setText("Satuan");

        JumlahLabel.setLabelFor(Jumlah);
        JumlahLabel.setText("Jumlah");

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Satuan", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableBarang.setColumnSelectionAllowed(true);
        TableBarang.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TableBarang);
        TableBarang.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TableBarang.getColumnModel().getColumnCount() > 0) {
            TableBarang.getColumnModel().getColumn(0).setResizable(false);
            TableBarang.getColumnModel().getColumn(1).setResizable(false);
            TableBarang.getColumnModel().getColumn(2).setResizable(false);
            TableBarang.getColumnModel().getColumn(3).setResizable(false);
        }

        SimpanBtn.setText("Simpan");
        SimpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanBtnActionPerformed(evt);
            }
        });

        BatalBtn.setText("Batal");
        BatalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        SearchLabel.setText("Cari");

        SearchBtn.setText("Cari");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KodeBarangLabel)
                            .addComponent(NamaBarangLabel)
                            .addComponent(SatuanLabel)
                            .addComponent(JumlahLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KodeBarang)
                            .addComponent(NamaBarang)
                            .addComponent(Satuan)
                            .addComponent(Jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SimpanBtn)
                            .addGap(18, 18, 18)
                            .addComponent(EditBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatalBtn))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(SearchBtn)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LogoutBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KodeBarangLabel)
                    .addComponent(KodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaBarangLabel)
                    .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SatuanLabel)
                    .addComponent(Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JumlahLabel)
                    .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanBtn)
                    .addComponent(BatalBtn)
                    .addComponent(EditBtn))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchLabel)
                    .addComponent(SearchBtn))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBtnActionPerformed
        if (
                !this.KodeBarang.getText().equals("") && 
                !this.Satuan.getText().equals("") &&
                !this.Jumlah.getText().equals("") &&
                !this.NamaBarang.getText().equals("")
            ) {
            this.saveData();
        } else {
            JOptionPane.showMessageDialog(this, "Kolom tidak boleh kosong");
        } 
    }//GEN-LAST:event_SimpanBtnActionPerformed

    private void BatalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalBtnActionPerformed
        this.emptyFields();
        this.showDataToTable();
        
        this.KodeBarang.setEnabled(true);
        this.SimpanBtn.setEnabled(true);
        this.Search.setText("");
    }//GEN-LAST:event_BatalBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        if ( ! this.Search.getText().equals("")) {
            this.searchData();
        } else {
            JOptionPane.showMessageDialog(this, "Kolom tidak boleh kosong");
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        if (
                !this.KodeBarang.getText().equals("") && 
                !this.Satuan.getText().equals("") &&
                !this.Jumlah.getText().equals("") &&
                !this.NamaBarang.getText().equals("")
            ) {
            this.updateData();
        } else {
            JOptionPane.showMessageDialog(this, "Kolom tidak boleh kosong");
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField Jumlah;
    private javax.swing.JLabel JumlahLabel;
    private javax.swing.JTextField KodeBarang;
    private javax.swing.JLabel KodeBarangLabel;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JLabel NamaBarangLabel;
    private javax.swing.JTextField Satuan;
    private javax.swing.JLabel SatuanLabel;
    private javax.swing.JTextField Search;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JButton SimpanBtn;
    private javax.swing.JTable TableBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
